version: '3.4'

services:
  ldapconnectiondemo:
    image: ${DOCKER_REGISTRY-}ldapconnectiondemo
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - myopenldap

  myphpldapadmin:
    image: osixia/phpldapadmin:${PHPLDAPADMIN_TAG}
    container_name: myphpldapadmin
    depends_on:
      - myopenldap

  myopenldap:
    image: osixia/openldap:${OPENLDAP_TAG}
    container_name: myopenldap