version: '3.4'

services:
  ldapconnectiondemo:
    image: ${DOCKER_REGISTRY-}ldapconnectiondemo
    container_name: ldapconnectiondemo
    depends_on:
      - myopenldap
    networks:
      - myldap-network
    restart: unless-stopped

  myphpldapadmin:
    image: osixia/phpldapadmin:${PHPLDAPADMIN_TAG}
    container_name: myphpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: myopenldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - "8056:80"
    depends_on:
      - myopenldap
    networks:
      - myldap-network
    restart: unless-stopped

  myopenldap:
    image: osixia/openldap:${OPENLDAP_TAG}
    container_name: myopenldap
    environment:
      - LDAP_ORGANISATION=MySystem
      - LDAP_DOMAIN=mydomain.home
      - LDAP_ADMIN_PASSWORD=${OPENLDAP_PASS}
      - LDAP_BASE_DN=dc=mydomain,dc=home
    ports:
      - "389:389"
    command: --copy-service
    volumes:
      - ./openldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
      - ./volumes/openldap/data:/var/lib/ldap
      - ./volumes/openldap/config:/etc/ldap/slapd.d
    networks:
      - myldap-network
    restart: unless-stopped

networks:
  myldap-network:
    name: myldap-network
    driver: bridge